# Generated by Django 5.0.4 on 2024-04-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('clabe_bancaria', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('clabe_bancaria', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=45)),
                ('last_login_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('transferencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'transferencia',
                'managed': False,
            },
        ),
    ]
